MODEL:


TRAIN:
  train_data_dir: [
   
  ]
  train_data_dir0: [
    
    
  ]
  batch_size: 35
  width: 128
  height: 32
  epochs: 500
  cuda: True
  ngpu: 1
  workers: 8   #8
  resume: ''
  ckpt_dir: './ckpt/'
  voc_type: 'all' #'digits lower upper all'
  saveInterval: 200 #200
  displayInterval: 100 #display loss 100
  adadelta: False
  lr: 0.001
  adam: True
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2

  VAL:
    val_data_dir: [
     
    ]
    val_data_dir0: [
     
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 400 #-1, val at the end of epoch 400
    texrnet_pretrained: 
    rec_pretrained: 
    moran_pretrained:
    crnn_pretrained: 
    autostr_pretrained: 
    

TEST:
  checkpoint: ''
  test_data_dir: [
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10